language: ruby

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - 2.3.0
  - ruby-head
  - rbx-2
  - jruby-9.0.4.0
  - jruby-head

jdk:
  - oraclejdk8

before_install:
  - '[ "$JRUBY_OPTS" != "" ] && export JRUBY_OPTS="--dev -Xcli.debug=true --debug"'

install: bundle install --path=vendor/bundle --retry=3 --jobs=3 --without bench
cache:
  directories:
    - vendor/bundle

script:
  - bundle exec rake ci

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=master"

matrix:
  exclude:
  - rvm: 2.0.0
    env: RAILS_VERSION=master
  - rvm: 2.1
    env: RAILS_VERSION=master
  - rvm: jruby-9.0.4.0
    env: RAILS_VERSION=master
  - rvm: jruby-9.0.4.0
    env: RAILS_VERSION=4.0
  - rvm: jruby-head
    env: RAILS_VERSION=master
  - rvm: jruby-head
    env: RAILS_VERSION=4.0
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
